# permissions for end users to view fruits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fruit-viewer-role
rules:
- apiGroups:
  - plants.siddharth.com
  resources:
  - fruits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - plants.siddharth.com
  resources:
  - fruits/status
  verbs:
  - get
